import{a as q,S,i}from"./assets/vendor-30VqbI-A.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const w="49318399-651ca0146c73ba5cb36d392c8",v="https://pixabay.com/api/";async function f(s,r){const t={key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await q.get(v,{params:t})).data}const m=document.querySelector(".gallery");let u=null;function g(s){const r=s.map(({webformatURL:t,largeImageURL:n,tags:e,likes:o,views:a,comments:b,downloads:L})=>`<li>
          <a href="${n}">
            <img src="${t}" alt="${e}" loading="lazy"/>
          </a>
          <div class="info">
            <p><b>Likes:</b>${o}</p>
            <p><b>Views:</b>${a}</p>
            <p><b>Comments:</b>${b}</p>
            <p><b>Downloads:</b>${L}</p>
          </div>
        </li>`).join("");m.insertAdjacentHTML("beforeend",r),u?u.refresh():u=new S(".gallery a")}function p(){m.innerHTML=""}function E(){document.querySelector(".loader").style.display="block"}function h(){document.querySelector(".loader").style.display="none"}function P(){const{height:s}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}const d=document.querySelector(".form"),$=d.querySelector("input"),c=document.querySelector(".js-load-more");let l=1,y="";i.info({title:"Hello",message:"Please enter a search query",position:"center"});c.style.display="none";h();d.addEventListener("submit",async s=>{s.preventDefault();const r=$.value.trim();if(console.log(r),!r){console.log("Empty query detected"),i.warning({title:"Warning",message:"Please enter a search query correctly"}),p();return}y=r,l=1,p(),c.style.display="none",E();try{const t=await f(y,l),{hits:n,totalHits:e}=t;console.log(t),n.length===0?(i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topLeft"}),d.reset()):(g(n),c.style.display=t.hits.length<e?"block":"none")}catch(t){console.log(t),i.error({title:"Error",message:`${t.message}`,position:"topRight"})}finally{h()}});c.addEventListener("click",async()=>{l+=1;try{const s=await f(y,l),{hits:r,totalHits:t}=s;g(r),P(),l*15>=t&&(c.style.display="none",i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"center"}))}catch(s){i.error({title:"Error",message:`${s.message}`,position:"topRight"})}});
//# sourceMappingURL=index.js.map
